name: CI

on:
  push:
    branches:
      - main

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "Hello, CI!"
